data_directory      = '~/work/data/sdss/raw/';
processed_directory = '~/work/data/sdss/processed/';
results_directory   = '~/work/results/dlas/';

filename = @(plate, mjd, fiber) ...
    ([data_directory ...
      num2str(plate) '/spec-' ...
      num2str(plate) '-' ...
      num2str(mjd)   '-' ...
      num2str(fiber, '%04i') '.fits']);

transition_wavelength = 1215.668;
convert_z = @(z) ((z + 1) * transition_wavelength);
